//! Structured planning proposal schema for Plexis.
//!
//! Represents the intermediate, uncommitted plan produced by an AI planner
//! before system validation and durable task graph mutation.

use serde::{Deserialize, Serialize};

/// High-level execution strategy recommended by the planner.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum ExecutionStrategy {
    /// Execute independent tasks concurrently whenever possible.
    Parallel,
    /// Execute tasks sequentially in topological order.
    Sequential,
    /// Execute tasks in distinct staged cohorts.
    Staged,
}

impl Default for ExecutionStrategy {
    fn default() -> Self {
        Self::Parallel
    }
}

/// Verification strategy recommended by the planner.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum VerificationStrategy {
    /// Inspect disk artifacts directly (presence, content, checksum).
    DiskArtifacts,
    /// Run verification command and check exit code/output.
    CommandOutput,
    /// Multi-step inspection combining disk artifacts and commands.
    MultiStep,
}

impl Default for VerificationStrategy {
    fn default() -> Self {
        Self::DiskArtifacts
    }
}

/// A proposed task within a planning proposal.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct ProposedTask {
    /// Temporary local identifier used to specify intra-plan dependencies (e.g. "task-1").
    pub temp_id: String,
    /// High-level objective statement.
    pub objective: String,
    /// Detailed instructions, scope, and technical context.
    #[serde(default)]
    pub description: Option<String>,
    /// Concrete verifiable acceptance criteria (e.g. "file:src/lib.rs").
    pub criteria: Vec<String>,
    /// Required capabilities (e.g. ["filesystem_write", "shell_execute"]).
    #[serde(default)]
    pub required_capabilities: Vec<String>,
    /// Suggested agent role (e.g. "Architect", "Code Implementer", "Tester").
    #[serde(default)]
    pub suggested_role: Option<String>,
    /// Relative execution priority.
    #[serde(default)]
    pub priority: i32,
}

/// A proposed dependency edge between two proposed tasks.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct ProposedDependency {
    /// Temporary ID of the task that must wait.
    pub task_temp_id: String,
    /// Temporary ID of the prerequisite task that must be verified first.
    pub depends_on_temp_id: String,
}

/// A complete, validated planning proposal generated by a planner.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct PlanProposal {
    /// High-level objective this plan addresses.
    pub objective: String,
    /// Technical rationale and architectural breakdown.
    pub rationale: String,
    /// The decomposed tasks.
    pub tasks: Vec<ProposedTask>,
    /// Directed dependencies between proposed tasks.
    #[serde(default)]
    pub dependencies: Vec<ProposedDependency>,
    /// Execution strategy.
    #[serde(default)]
    pub execution_strategy: ExecutionStrategy,
    /// Verification strategy.
    #[serde(default)]
    pub verification_strategy: VerificationStrategy,
}

impl PlanProposal {
    pub fn new(objective: impl Into<String>, rationale: impl Into<String>) -> Self {
        Self {
            objective: objective.into(),
            rationale: rationale.into(),
            tasks: Vec::new(),
            dependencies: Vec::new(),
            execution_strategy: ExecutionStrategy::Parallel,
            verification_strategy: VerificationStrategy::DiskArtifacts,
        }
    }

    pub fn with_task(mut self, task: ProposedTask) -> Self {
        self.tasks.push(task);
        self
    }

    pub fn with_dependency(
        mut self,
        task_temp_id: impl Into<String>,
        depends_on_temp_id: impl Into<String>,
    ) -> Self {
        self.dependencies.push(ProposedDependency {
            task_temp_id: task_temp_id.into(),
            depends_on_temp_id: depends_on_temp_id.into(),
        });
        self
    }
}
