//! Persistent Planning domain models for Plexis.
//!
//! Stores the complete provenance of planner requests, model parameters,
//! structured proposals, validation reports, and applied graph mutations.

use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};

use crate::ids::{PlanId, TaskId, WorkflowId};

/// Lifecycle status of a planning proposal.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum PlanStatus {
    /// Proposal was generated by the planner.
    Proposed,
    /// Proposal successfully passed invariant validation.
    Validated,
    /// Proposal was transactionally applied to the task graph.
    Applied,
    /// Proposal was rejected due to validation failure or policy denial.
    Rejected,
}

impl PlanStatus {
    pub fn as_str(&self) -> &'static str {
        match self {
            PlanStatus::Proposed => "proposed",
            PlanStatus::Validated => "validated",
            PlanStatus::Applied => "applied",
            PlanStatus::Rejected => "rejected",
        }
    }
}

/// Durable audit record of a planning run.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct PlanningRecord {
    /// Unique plan identifier.
    pub id: PlanId,
    /// Associated workflow.
    pub workflow_id: WorkflowId,
    /// Optional parent task if this was dynamic decomposition of an existing task.
    pub parent_task_id: Option<TaskId>,
    /// High-level objective passed to the planner.
    pub objective: String,
    /// AI provider adapter name used for planning.
    pub provider: String,
    /// Model name used for planning.
    pub model: String,
    /// Full structured proposal JSON.
    pub proposal: serde_json::Value,
    /// Lifecycle status.
    pub status: PlanStatus,
    /// Validation errors if validation failed.
    pub validation_errors: Vec<String>,
    /// Structured list of created task IDs and dependency edges.
    pub applied_mutations: serde_json::Value,
    /// Planning latency in milliseconds.
    pub latency_ms: u64,
    /// Number of prompt tokens consumed.
    pub prompt_tokens: Option<u32>,
    /// Number of completion tokens produced.
    pub completion_tokens: Option<u32>,
    /// Creation timestamp.
    pub created_at: DateTime<Utc>,
}

impl PlanningRecord {
    pub fn new(
        workflow_id: WorkflowId,
        objective: impl Into<String>,
        provider: impl Into<String>,
        model: impl Into<String>,
        proposal: serde_json::Value,
    ) -> Self {
        Self {
            id: PlanId::new(),
            workflow_id,
            parent_task_id: None,
            objective: objective.into(),
            provider: provider.into(),
            model: model.into(),
            proposal,
            status: PlanStatus::Proposed,
            validation_errors: Vec::new(),
            applied_mutations: serde_json::Value::Null,
            latency_ms: 0,
            prompt_tokens: None,
            completion_tokens: None,
            created_at: Utc::now(),
        }
    }

    pub fn with_parent_task(mut self, parent_task_id: TaskId) -> Self {
        self.parent_task_id = Some(parent_task_id);
        self
    }

    pub fn with_validation(mut self, is_valid: bool, errors: Vec<String>) -> Self {
        if is_valid {
            self.status = PlanStatus::Validated;
        } else {
            self.status = PlanStatus::Rejected;
            self.validation_errors = errors;
        }
        self
    }

    pub fn mark_applied(mut self, applied_mutations: serde_json::Value) -> Self {
        self.status = PlanStatus::Applied;
        self.applied_mutations = applied_mutations;
        self
    }

    pub fn with_telemetry(
        mut self,
        latency_ms: u64,
        prompt_tokens: Option<u32>,
        completion_tokens: Option<u32>,
    ) -> Self {
        self.latency_ms = latency_ms;
        self.prompt_tokens = prompt_tokens;
        self.completion_tokens = completion_tokens;
        self
    }
}
